# numpy의 자료형
## numpy자료형 형 선언
- `dtype`사용

In [6]:
import numpy as np
a = np.array([1,2,3], dtype=int)

In [7]:
a

array([1, 2, 3])

In [9]:
a.dtype

dtype('int32')

|dtype 접두사 | 설명 | 사용예 |
|--- | --- | --- |
| b | boolean | b(true or false) |
| i | integer | i8(64bit) |
| u | unsigned integer | u8(64bit) |
| f | foating | f8(64bit) |
| c | complex floating number | c16(128bit) |
| o | Oject | 0 ( point of Object ) |
| s | byte array string | S24 ( 24 word ) |
| U | Unicode String | U24(24 Unicode string) |

## INF and Nan

In [10]:
np.array([0,1,-1,0]) / np.array([1,0,0,0])
np.log(0)
np.exp(-np.inf)

C:\Users\73673\AppData\Local\Temp\ipykernel_10004\980809747.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.array([0,1,-1,0]) / np.array([1,0,0,0])
C:\Users\73673\AppData\Local\Temp\ipykernel_10004\980809747.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.array([0,1,-1,0]) / np.array([1,0,0,0])
C:\Users\73673\AppData\Local\Temp\ipykernel_10004\980809747.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(0)


0.0

## Numpy Array make

- zeros, ones
- zeros_like, ones_like
- empty
- arange
- linspace, logspace
- zeros



In [11]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [12]:
b = np.zeros((2,3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
c = np.zeros((5,2), dtype="i")
c

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [14]:
d = np.zeros(5, dtype="U4")
d

array(['', '', '', '', ''], dtype='<U4')

In [16]:
d[0] = "abc"
d[1] = "abcd"
d[2] = "ABCDE" #크기가 잘림. ( 4이상 string )
d

array(['abc', 'abcd', 'ABCD', '', ''], dtype='<U4')

In [17]:
e = np.ones((2,3,4), dtype="i8")
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int64)

In [18]:
f = np.ones_like(b, dtype="f")
f

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [19]:
g = np.empty((4,3))
g

array([[1.23288543e-311, 3.16202013e-322, 0.00000000e+000],
       [0.00000000e+000, 1.10343781e-312, 3.15776051e-033],
       [1.96751858e+160, 3.85591199e-057, 4.04570187e-057],
       [1.22231713e+161, 1.05841536e+165, 8.61692771e-043]])

In [22]:
np.arange(10) # 0... n-1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(3,21,2) # start, end, step number

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [24]:
np.linspace(0,100,5) # start, end, count number

array([  0.,  25.,  50.,  75., 100.])

In [25]:
np.logspace(0.1,1,10)

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

## 전치 연산 ( transpose ) 

- 행과 열을 변경

In [27]:
A = np.array([[1,2,3], [4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

## 배열의 크기 변형

- 일단 만들어진 배열의 내부 데이터는 보존한 채로 형태만 바꾸려면 reshape 명령이나 메서드를 사용한다. 예를 들어 12개의 원소를 가진 1차원 행렬은 3x4 형태의 2차원 행렬로 만들 수 있다.

In [29]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [30]:
b = a.reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
a.reshape(3,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
a.reshape(2,2,-1)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [33]:
a.reshape(2,-1,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [34]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [36]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

배열 사용에서 주의할 점은 길이가 5인 1차원 배열과 행, 열의 갯수가 (5,1)인 2차원 배열 또는 행, 열의 갯수가 (1, 5)인 2차원 배열은 데이터가 같아도 엄연히 다른 객체라는 점이다.

In [37]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [38]:
x.reshape(1,5)

array([[0, 1, 2, 3, 4]])

In [39]:
x.reshape(5,1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [40]:
x[:,np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])