# 배열 연산
## 벡터화 연산
앞서 넘파이가 벡터화 연산(vectorized operation)을 지원한다고 이야기하였다. 벡터화 연산을 쓰면 명시적으로 반복문을 사용하지 않고도 배열의 모든 원소에 대해 반복연산을 할 수 있다. 벡터화 연산의 또다른 장점은 선형 대수 공식과 동일한 아주 간단한 파이썬 코드를 작성할 수 있다는 점이다.

예를 들어 선형 대수에서 두 벡터의 합은 다음과 같이 구한다.


$$x = \begin{bmatrix} 1 \\ 2 \\ 3 \\ . \\ . \\ . \\ 10000 \end{bmatrix}$$, $$y = \begin{bmatrix} 1001 \\ 1002 \\ 1003 \\ . \\ . \\ . \\ 20000 \end{bmatrix}$$

In [2]:
import numpy as np

In [3]:
x = np.arange(1,10001)
y = np.arange(10001, 20001)

In [4]:
z = np.zeros_like(x)
z

array([0, 0, 0, ..., 0, 0, 0])

만약 벡터화 연산을 사용하지 않는다면 이 연산은 반복문을 사용하여 다음과 같이 만들어야 한다. 이 코드에서 `%%time`은 셀 코드의 실행시간을 측정하는 아이파이썬(IPython) 매직(magic) 명령이다.

In [5]:
%%time
for i in range(10000):
    z[i] = x[i] + y[i]

CPU times: total: 31.2 ms
Wall time: 4.99 ms


In [6]:
z[:10]

array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020])

In [7]:
%%time
z = x + y

CPU times: total: 0 ns
Wall time: 0 ns


In [8]:
z[:10]

array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020])

논리 연산도 가능

In [9]:
a = np.array([1,2,3,4])
b = np.array([4,2,2,4])
a == b

array([False,  True, False,  True])